### ISSUE TITLE
Regler för design

### ISSUE THREAD

**Issue by puffisbre** [puffisbre/team-9-quiz-app#3]

**Comment by MladenKovacic** [comment]
Färgerna utgår vi ifrån Figma skissen.

Vi börjar med 600 pixlar (max) mobile. nästa brytpunkt tablet 992 pixlar(max), nästa brytpunkt desktop 1200 pixlar

https://www.w3schools.com/howto/howto_css_media_query_breakpoints.asp

Font:  ?

Hur ska classerna se ut när vi skriver dom i html exempel: (main-container)
